### ISSUE TITLE
Async Function.

### ISSUE THREAD

**Issue by Bleez103** [luqmaan/oihclamirt#1]
I'm getting this error below on first run. How would I got by resolving this?

C:\Users\Administrator\oihclamirt\scraper.js:21
async function scrapeAtomFeed(url) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Administrator\oihclamirt\index.js:4:18)

**Comment by luqmaan** [comment]
It's probably because the version of node you have installed doesn't have async/await. You need node 8 or higher.

To check your current node version:

```sh
node -v
v8.1.2
```

Try installing the latest version of node: https://nodejs.org/en/download/.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function

**Comment by Bleez103** [comment]
Upgrading to Node 8 solved the above issue I was having. Thanks for the reply.. I will close this issue.

**Comment by Bleez103** [comment]
The bot works well and thanks for the time and creating it. I have a few questions.

When running the shell script it seems to repost previous announced items. Will it at some point stop reposting the old announced items and only newly added items?

Is there a way to a maybe add small .jpg of the announce item or would that be a bad idea?
![image](https://user-images.githubusercontent.com/25425376/30221281-8381e804-9477-11e7-86c8-ec185e8f3105.png)

Last one.

Will there be an automated checkout option added once a particular linked is clicked?

Also, thanks again for your amazing work. If there is a way to make an donation let me know as well.

**Comment by luqmaan** [comment]
> Will it at some point stop reposting the old announced items and only newly added items?

Maybe. I don't really use this script and don't plan to use it for a while (maybe next yeezy drop). Right now I'm focusing on improving kickdb.com.

@sixsneakers on twitter wants to add this, and is learning javascript so he can add it.

> Will there be an automated checkout option added once a particular linked is clicked?

That's something I had hoped to add. I refactored trimalchio so I could use its checkout functionality in this script. https://github.com/dzt/trimalchio/pull/3. This repo is open source so you could always add it yourself. 😸 

> If there is a way to make an donation let me know as well.

The best donation for me would be to let other people know about http://kickdb.com/.

**Comment by Bleez103** [comment]
Thanks for the input. I'll pass along the information.

**Comment by luqmaan** [comment]
> Is there a way to a maybe add small .jpg of the announce item or would that be a bad idea?

There is a way.  https://api.slack.com/docs/message-attachments

**Comment by Bleez103** [comment]
I'll look into it and see if I can figure out how to implement it.
